### ISSUE TITLE
如何修改模板文件？

### ISSUE THREAD

**Issue by huangqian8** [r12f/hexo-tag-post-link#1]
请教一下，如果不想在每篇文章内添加一次代码，应该修改哪个模板文件呢？

**Comment by r12f** [comment]
多谢反馈，我已经把这个功能加好了：https://github.com/r12f/hexo-tag-post-link/commit/671e4da0f68a46de4548f5a1a5de1cbcba1a7ed2

现在只需要用`npm update`升级到新版本，然后就可以通过_config.yml来控制添加什么模板到文章的开头或者结尾了：
```
post_link:
  insert_before_post: header
  insert_after_post: footer
```

**Comment by huangqian8** [comment]
post页面测试正常，但现在在page页面也出现了，期待修正一下。
