### ISSUE TITLE
页面生成链接bug

### ISSUE THREAD

**Issue by huangqian8** [r12f/hexo-tag-post-link#2]
你好，反馈个问题。目前post页面自动生成链接正常，但我有2个page页面分别是“留言”和“关于”，这两个页面上也自动生成了链接。需要添加判断语句，区别post和page页面。

**Comment by r12f** [comment]
非常感谢！已经修正好了~ 现在全局的页面链接只会给layout为post的页面添加，升级到1.0.5版本就没有这个问题了~
